experiment_name: "MeshNCA"
task: "meshnca"
device: "cuda:0"

meshnca:
  channels: 16 # Number of nca channels
  fc_dim: 128 # Number of neurons in the hidden layer
  sh_order: 1 # Degree of the spherical harmonics
  aggregation: "mean" # Aggregation method for the perception stage. Options: sum, mean
  stochastic_update: True # Whether to use stochastic update in the NCA update
  seed_mode: "zeros" # Initial state of the NCA. Options: zeros, random
  condition: null # Condition for the NCA. Options: null, "MPE", "CPE"
  graft_initialization: null # Either null or a path to a pretrained model

siren:
  hidden_features: 32 # Number of neurons in the hidden layer of the SIREN decoder
  hidden_layers: 2 # Number of hidden layers in the SIREN decoder
  outermost_linear: True # Whether to use a linear layer at the output of the SIREN decoder
  fx: "linear" # The preactivation function before the sin. ["linear", "finer", "sinh"]
  activation: "sin"
  num_frequencies: 0 # Number of frequencies in the SIREN decoder
  first_omega_0: 10.0
  hidden_omega_0: 10.0

train:
  epochs: 3000 # Number of epochs
  batch_size: 2 # Batch size
  lr: 0.001 # Learning rate
  lr_decay_steps: [ 1000, 2000 ] # Learning rate decay steps
  lr_decay_gamma: 0.3 # Learning rate decay factor

  #### MeshNCA related configs ####
  pool_size: 512 # Number of samples in the pool. Pool is used to improve long-term stability of MeshNCA
  inject_seed_interval: 32 # Number of steps after which a seed state is injected into the pool
  step_range: [ 32, 96 ] # Number of update steps during training is sampled randomly from this range

  #### Rendering related configs ####
  camera:
    height: 1024 # Height of the rendered image (Number of pixels in the camera)
    width: 1024 # Width of the rendered image (Number of pixels in the camera)
    num_views: 1 # Number of random views used fo training. In the paper, we used 6 views
    distance: 2.3 # Distance of the camera from the origin
    max_elevation: 180.0 # Maximum elevation angle of the camera
    max_azimuth: 360.0 # Maximum azimuth angle of the camera
    k: 1.0 # k=1.0 means the camera is perspective. As k increases the camera becomes more orthographic
  icosphere:
    subdivision_freq: 64 # Frequency of the icosphere subdivision. 64 = 2 ** 6

  test_mesh:
    obj_path: "data/meshes/mug/mug.obj" # Path to the test mesh
    subdivision_iter: 1 # Number of subdivision iterations for the test mesh

  summary_interval: 250 # Interval for logging the training summary

  # Config related to Sphere projection used to render the icosphere mesh during training
  projection:
    height: 1024 # Height of the rendered image
    width: 1024 # Width of the rendered image
    max_elevation: 90.0 # Maximum value for the elevation of the center of the patch
    max_azimuth: 180.0 # Maximum value for the azimuth of the center of the patch
    max_range: 0.4 # This determines the relative size of the patch to the size of the sphere. 1.0 will cover the whole sphere. To avoid distortions use values < 0.6
    num_views: 1 # Number of views to sample from the cached projections for each batch
    max_views: 120 # Number of random views to generate
    save_path: "data/projections/" # Path to save the cached projections

renderer:
  ambient_light: 1.0 # Ambient light intensity
  directional_light: 0.0 # Directional light intensity
  background_color: 0.0 # Background color in gray scale. 1.0 = white, 0.0 = black
  # "ray" to use sphere projection and "raster" to use perspective camera 
  vs_shader: "ray" # The rendering mode to use, either "raster" or "ray"
  fs_shader: "vanilla" # The fragment shader to use. Either "vanilla" or "simple" or "pbr"

test_renderer:
  ambient_light: 0.5 # Ambient light intensity
  point_light: 0.4 # Point Light Intensity
  background_color: 1.0 # Background color in gray scale. 1.0 = white, 0.0 = black
  vs_shader: "raster" # The rendering mode to use, either "raster" or "ray"
  fs_shader: "pbr" # The fragment shader to use. Either "vanilla" or "simple" or "pbr"

num_channels:
  {
    # Number of channels in the model to assign to each target image
    "rgb": 3
  }

loss:
  overflow_loss_weight: 100.0 # Weight of the overflow loss
  appearance_loss_weight: 2.0 # Weight of the style loss

  #### Appearance loss used for image-guided training. Mostly based on VGG features ####
  appearance_loss_kwargs:
    target_image_size: [ 1024, 1024 ] # Resolution for loading the target images
    patch_size: [ 256, 256 ] # Crops from the generated images will be resized to this size before passing to VGG
    num_scales: 3 # Number of scales to be used for the style loss
    relative_scale: 2 # Relative scale of the target image to the generated image. 1.0 = same size, 2.0 = twice the size
    max_image_size: [ 1024, 1024 ] # Images larger than this size will be center cropped (Used to avoid OOM errors when relative scale is large)
    # The single channel images will be expanded to 3 channels for evaluating the VGG-based style loss
    target_images_path:
      {
        # Paths to the target images for the appearance loss. The keys should correspond to the keys in num_channels
        "rgb": "data/textures_hr/bubbly_0101.jpg"
      }
    include_image_as_feature: False
    num_pseudo_targets: 10
    vgg_layers: [ 1, 6, 11, 18, 25 ] # VGG layers to be used for the style loss

logger:
  backend: local
